# Generated by Django 3.2.4 on 2021-07-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210703_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('slider_id', models.AutoField(primary_key=True, serialize=False)),
                ('slider_name', models.CharField(max_length=100)),
                ('slider_image', models.ImageField(default='', upload_to='dashboard/slider')),
                ('InsertedDate', models.DateField(null=True)),
                ('UpdatedDate', models.DateField(null=True)),
                ('IsActive', models.BooleanField(default=1, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='IsActive',
        ),
        migrations.RenameField(
            model_name='sub_category',
            old_name='status',
            new_name='IsActive',
        ),
    ]
