# Generated by Django 3.2.4 on 2021-07-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210710_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='UpdatedDate',
            field=models.DateField(default='', null=True),
        ),
    ]
