# Generated by Django 3.2.4 on 2021-07-10 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_slider_updateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='InsertedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='IsActive',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='slider',
            name='UpdatedDate',
            field=models.DateTimeField(),
        ),
    ]
