# Generated by Django 3.2.4 on 2021-07-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210715_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='', upload_to='dashboard/category'),
        ),
    ]
