# Generated by Django 3.2.4 on 2021-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500)),
                ('head0', models.CharField(default='', max_length=5000)),
                ('head1', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(default='', max_length=5000)),
                ('publish_date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='shop/images')),
            ],
        ),
    ]
