# Generated by Django 3.2 on 2021-04-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='imag',
            field=models.ImageField(default='', upload_to='shop/img'),
        ),
    ]
