# Generated by Django 3.2 on 2021-05-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210421_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=70)),
                ('email', models.CharField(default='', max_length=90)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
