# Generated by Django 3.2.4 on 2021-06-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
