# Generated by Django 3.2.4 on 2021-07-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orders_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imag',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to='shop/img'),
        ),
    ]
