# Generated by Django 3.2.4 on 2021-07-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210719_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='imag',
        ),
    ]
